---
name: 🧹Chore or task
about: Identify a necessary task to be addressed.
title: ''
labels: 'kind/chore'
assignees: ''
---
### Current Behavior
<!-- A brief description of what the current circumstance is. -->

### Desired Situation
<!-- A brief description of the necessary action to take. -->

---
<img src="https://raw.githubusercontent.com/khulnasoft/khulnasoft/master/.github/assets/images/khulnasoft/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://khulnasoft.com/community/handbook">Handbook</a></h2>

The khulnasoft.com website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/khulnasoft/khulnasoft/tree/master).
- 📚 See [contributing instructions](https://github.com/khulnasoft/khulnasoft/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for KhulnaSoft site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/KhulnaSoft-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.khulnasoft.com) and [Community Slack](https://slack.khulnasoft.com).

<img src="https://raw.githubusercontent.com/khulnasoft/khulnasoft/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the KhulnaSoft Community by submitting your [community member form](https://khulnasoft.com/newcomer).
